### ISSUE TITLE
Timeout in rake userlist:import 

### ISSUE THREAD

**Issue by joshuap** [userlist/userlist-rails#4]
I'm running the `rake userlist:import` task, and it was going great until a random timeout killed it (backtrace attached). When this happened, it was not apparent how to restart the task without iterating over all of my users again. I ended up hacking the rake task, adding `user_model.where('id > 1233')` here:

https://github.com/userlist/userlist-rails/blob/8fd0ba0e5d056561810191d204c044441d7dc545/lib/userlist/rails/tasks/userlist.rake#L11

The task is now working again. It would be nice to retry timeouts, and/or add an official way to resume the task without starting over.

```
Pushing User 1234...rake aborted!
Net::OpenTimeout: execution expired
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-0.6.0/lib/userlist/push/client.rb:60:in `request'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-0.6.0/lib/userlist/push/client.rb:23:in `post'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-0.6.0/lib/userlist/push/strategies/direct.rb:10:in `public_send'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-0.6.0/lib/userlist/push/strategies/direct.rb:10:in `call'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-0.6.0/lib/userlist/push/operations/create.rb:9:in `create'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-rails-0.6.1/lib/userlist/rails/tasks/userlist.rake:12:in `block (4 levels) in <main>'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-rails-0.6.1/lib/userlist/rails/importer.rb:12:in `instance_exec'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-rails-0.6.1/lib/userlist/rails/importer.rb:12:in `block in import'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/relation/batches.rb:71:in `block (2 levels) in find_each'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/relation/batches.rb:71:in `each'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/relation/batches.rb:71:in `block in find_each'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/relation/batches.rb:229:in `loop'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/relation/batches.rb:229:in `in_batches'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/relation/batches.rb:70:in `find_each'
/home/app/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/querying.rb:22:in `find_each'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-rails-0.6.1/lib/userlist/rails/importer.rb:27:in `find_each'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-rails-0.6.1/lib/userlist/rails/importer.rb:10:in `import'
/home/app/shared/bundle/ruby/2.7.0/gems/userlist-rails-0.6.1/lib/userlist/rails/tasks/userlist.rake:11:in `block (3 levels) in <main>'
/home/app/shared/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => userlist:import => userlist:import:users
(See full trace by running task with --trace)
```

**Comment by benedikt** [comment]
Hey @joshuap! 

I think we [found the underlying issue](https://github.com/userlist/userlist-ruby/commit/e094342f0ef55d3c1565fa3f930b699ae418b9a4) that caused this. Would you mind giving it a try at some point by updating the `userlist` gem to the latest version from GitHub?

Thanks!

**Comment by joshuap** [comment]
> Hey @joshuap!
> 
> I think we [found the underlying issue](https://github.com/userlist/userlist-ruby/commit/e094342f0ef55d3c1565fa3f930b699ae418b9a4) that caused this. Would you mind giving it a try at some point by updating the `userlist` gem to the latest version from GitHub?
> 
> Thanks!

I PR'd the update and will let you know if I have this issue again. It might be a while before I do another full import/update. 👍

**Comment by benedikt** [comment]
This seems to be fixed according to reports from other customers.
